services:
  # Your other services.

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: unless-stopped
    ports:
      - 3030:3000
    networks:
      - npm_net

networks:
  npm_net:
    external: true