#Official format for server
#First create a network
#Then create a volume
#Then create the service 
#using portainer

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Important for Docker
    # ports:
      # - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - npm_net

volumes:
  pgadmin_data:
    external: true

networks:
  npm_net:
    external: true
