services:
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:v0.49.1'
    devices:
      - /dev/kmsg
    privileged: true
    container_name: cadvisor
    ports:
      - '8080:8080'
    volumes:
      - '/dev/disk/:/dev/disk:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys:/sys:ro'
      - '/var/run:/var/run:ro'
      - '/:/rootfs:ro'
    networks:
      - npm_net

networks:
  npm_net:
    external: true
