version: '3.8'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5555:80"
    links:
      - pg
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin


volumes:
  pg_data:
  pgadmin_data: