#Official format for server
#First create a network
#Then create a volume
#Then create the service 
#using portainer

services:

  postgres:
    image: postgres #17.2 # Or your preferred version
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: alwArYwENCIL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/ # If you have initialization scripts
    # ports:
      # - "5432:5432"
    networks:
      - npm_net

volumes:
  postgres_data:
    external: true

networks:
  npm_net:
    external: true
