---
- name: Deploy Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Create and start services
      community.docker.docker_compose_v2:
        # Specify the path to the docker-compose.yml file
        # the path is relative to the playbook use pwd
        project_src: "{{ playbook_dir }}/nginx"
      register: output