---
- name: Deploy Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Deploy nginx
      community.docker.docker_container:
        name: test_nginx
        image: nginx:latest
        ports:
          - '8181:80'
