---
- name: Deploy Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Copy proj to the server
      copy:
        src: test_proj
        dest: /tmp/test_proj
        mode: '0755'

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "/tmp/test_proj"
      register: output

    - name: Cleanup the proj
      file:
        path: /tmp/test_proj
        state: absent
