services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:v2.11.2
    container_name: semaphore
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
    restart: unless-stopped
    networks:
      - npm_net

networks:
  npm_net:
    external: true

volumes:
  semaphore_data:
  semaphore_config:
  semaphore_tmp:
